version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: magic
      MYSQL_USER: librarian
      MYSQL_PASSWORD: library123
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web:
    build: 
      context: .
      dockerfile: web/Dockerfile
    depends_on: [db]
    ports: ['8080:80']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: librarian
      WORDPRESS_DB_PASSWORD: library123
      WORDPRESS_DB_NAME: magic
    volumes:
      - backups:/backups

volumes:
  db_data:
  backups:
